
services:
  postgres_db:
   image: postgres
   ports:
      - "5432:5432"
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DATABASE=postgres
     - POSTGRES_HOST_AUTH_METHOD=trust


  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
volumes:
  rabbitmq-data:

    #h2_db:
  #  image: openjdk:17.0.1-jdk-slim
  # ports:
  #   - "8081:8081"
  # environment:
  #   - SPRING_DATASOURCE_URL=jdbc:h2:mem:h2paymentdockerdb
  #   - SPRING_DATASOURCE_USERNAME=h2
  #   - SPRING_DATASOURCE_PASSWORD=
  # volumes:
    #   - ./build/libs:/app
  # command: [ "java", "-jar", "/app/ejercicio1-0.0.1-SNAPSHOT.jar" ]

